export const CountriesAmericas = [
  { name: 'Argentina', code: 'ar' },
  { name: 'Bolivia', code: 'bo' },
    { name: 'Brasil', code: 'br' },
    { name: 'Chile', code: 'cl' },
    { name: 'Colombia', code: 'co' },
    { name: 'Costa Rica', code: 'cr' },
    { name: 'Cuba', code: 'cu' },
    { name: 'Ecuador', code: 'ec' },
    { name: 'El Salvador', code: 'sv' },
    { name: 'Guatemala', code: 'gt' },
    { name: 'Honduras', code: 'hn' },
    { name: 'México', code: 'mx' },
    { name: 'Nicaragua', code: 'ni' },
    { name: 'Panama', code: 'pa' },
    { name: 'Paraguay', code: 'py' },
    { name: 'Perú', code: 'pe' },
    { name: 'Puerto Rico', code: 'pr' },
    { name: 'República Dominicana', code: 'do' },
    { name: 'Uruguay', code: 'uy' },
    { name: 'Venezuela', code: 've' },
    { name: 'Estados Unidos', code: 'us' },
    { name: 'Canadá', code: 'ca' },
    { name: 'Guayana Francesa', code: 'gf' },
    { name: 'Guayana', code: 'gy' },
    { name: 'Surinam', code: 'sr' },
    { name: 'Trinidad y Tobago', code: 'tt' },
    { name: 'Islas Malvinas', code: 'fk' },
    { name: 'Aruba', code: 'aw' },
    { name: 'Curazao', code: 'cw' },
    { name: 'Bonaire', code: 'bq' },
    { name: 'Saba', code: 'bq' },
    { name: 'San Eustaquio', code: 'bq' },
    { name: 'San Bartolomé', code: 'bl' },
    { name: 'San Martín', code: 'mf' },
    { name: 'Anguila', code: 'ai' },
    { name: 'Bermudas', code: 'bm' },
    { name: 'Islas Caimán', code: 'ky' },
    { name: 'Montserrat', code: 'ms' },
    ];